#!/bin/bash
	SOFT=octave
	CMD="$SOFT -q --eval"
	PROG=mandelbrot
echo --------------------------------------
echo Testing only sequential code, 3 times-
echo --------------------------------------
#	for (( C=1; C<=2*NC; C++ )); do
	       C=1
	  for (( T=1; T<=3; T++ )); do
		echo ___ $C Processes ___ turn $T ____
#		mpirun -c $C $CMD $PROG
			     $CMD $PROG
		sleep 1
#	  done
	done | tee -a $$

	mv $$ $PROG.$SOFT.log
#	grep "elapsed" $$ > $PROG.$SOFT.log
#	rm $$
